server:
  port: 8080
  context-path: /demo
application:
  name: springboot-properties
  version: 0.0.1-SNAPSHOT
  author:
    name: caoqiang
    website: ronghuaxueleng.cn
    qq: 353752092
    phone-number: 15901254680